// Common data wrappers keep each page focused on its own responsibilities.
export async function result(request) {
  const { data, error } = await request;
  if (error) throw error;
  return data;
}
export const rpc = (client, name, args) => result(client.rpc(name, args));

// Only accept UUID record links generated by the dashboards.
export function recordId() {
  const id = new URLSearchParams(window.location.search).get('id');
  if (!/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(id || '')) {
    throw new Error('Open this record from your dashboard.');
  }
  return id;
}

// Read a permitted loan and its related records together.
export async function loanBundle(client, id) {
  const [loan, statement, payments, documents, events] = await Promise.all([
    result(client.from('loan_applications').select('*').eq('id', id).single()),
    rpc(client, 'loan_statement', { p_id: id }),
    result(client.from('loan_payments').select('*').eq('application_id', id).order('paid_on')),
    result(client.from('application_documents').select('*').eq('application_id', id).order('created_at')),
    result(client.from('audit_events').select('action,created_at').eq('application_id', id).order('created_at')),
  ]);
  return { loan, statement, payments, documents, events };
}
